# Azure Pipeline for Next.js frontend (monorepo)
trigger:
  branches:
    include:
      - aure-pipelines   # only trigger on this branch

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm ci
    npm run lint -- --fix || true
    npm run build
  displayName: 'Install dependencies, lint, and build frontend'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'frontend/.next'
    artifactName: 'frontend-build'
    publishLocation: 'Container'
  displayName: 'Publish frontend build artifacts'
