pool:
  name: pool-1

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npx next lint --fix || true
  displayName: 'Run ESLint (auto-fix)'

- script: node --max-old-space-size=4096 ./node_modules/.bin/next build
  displayName: 'Build Next.js frontend'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.next'
    artifactName: 'frontend-build'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
